from typing import TypedDict, List
from langchain_ollama import ChatOllama
from pydantic import BaseModel, Field

class RetrievedDocument(BaseModel):
    content: str
    source_file: str

class FinalReport(BaseModel):
    summary: str
    key_takeaways: List[str]

class GraphState(TypedDict):
    """
    This is the state object passed between all our agents.
    """
    user_query: str                  
    sub_tasks: List[str]             
    retrieved_docs: List[RetrievedDocument] 
    current_draft: str               
    critic_feedback: str             
    revision_count: int              
   
    from langchain_ollama import ChatOllama

# 1. Initialize our local LLM engine (Qwen2.5:3b)
# temperature=0 kuduthurukkom, so that strict ah factual ah answer pannum.
llm = ChatOllama(model="qwen2.5:3b", temperature=0)

# 2. Define the exact structure we want from the Router
class RouterOutput(BaseModel):
    sub_tasks: List[str] = Field(description="List of step-by-step tasks to research the user's query")

# 3. Create the Router Agent Node (Function)
def router_node(state: GraphState):
    print("--- 🧠 ROUTER AGENT: Thinking ---")
    query = state["user_query"]
    
    # Prompting the LLM to act as a manager
    prompt = f"You are a research manager. Break down this complex query into 2 or 3 specific research tasks: {query}"
    
    # Force the LLM to reply strictly in our RouterOutput list format
    structured_llm = llm.with_structured_output(RouterOutput)
    response = structured_llm.invoke(prompt)
    
    # Update the shared note-book (state) with the new tasks
    return {"sub_tasks": response.sub_tasks}
if __name__ == "__main__":
    print("🚀 Script Starting...") # Ithu first print aaganum
    
    test_state = {
        "user_query": "Analyze Tesla's Q3 performance focusing on supply chain and net profit",
        "sub_tasks": [],
        "retrieved_docs": [],
        "current_draft": "",
        "critic_feedback": "",
        "revision_count": 0
    }
    
    print("⏳ hitting to the router...")
    updated_state = router_node(test_state)
    
    print("\n--- 📝 ROUTER OUTPUT (Updated Tasks) ---")
    print(updated_state)

    from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings

# Initialize the embedding model we downloaded (nomic-embed-text)
embeddings = OllamaEmbeddings(model="nomic-embed-text")

# --- DATABASE SETUP FUNCTION ---
def setup_vector_database(pdf_path: str):
    """Loads a PDF, chunks it, and saves it to a local Chroma database."""
    print(f"--- 📚 LOADING DOCUMENT: {pdf_path} ---")
    
    # 1. Load the PDF
    loader = PyPDFLoader(pdf_path)
    docs = loader.load()
    
    # 2. Split into chunks for Parent-Document Retrieval
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
    splits = text_splitter.split_documents(docs)
    
    # 3. Store in local ChromaDB
    print("--- 🗄️ STORING IN CHROMADB ---")
    vectorstore = Chroma.from_documents(
        documents=splits, 
        embedding=embeddings, 
        persist_directory="./chroma_db"
    )
    return vectorstore

# --- AGENT 2: RAG SPECIALIST ---
def rag_node(state: GraphState):
    """Searches the database using the sub-tasks generated by the Router."""
    print("--- 🔎 RAG SPECIALIST: Searching Database ---")
    
    # Connect to the existing local database
    vectorstore = Chroma(persist_directory="./chroma_db", embedding_function=embeddings)
    
    # Set the retriever to fetch the top 2 most relevant chunks
    retriever = vectorstore.as_retriever(search_kwargs={"k": 2})
    
    # Get the first sub-task created by the Router to use as the search query
    search_query = state["sub_tasks"][0]
    print(f"Executing Search Query: {search_query[:50]}...")
    
    # Fetch matching documents
    docs = retriever.invoke(search_query)
    
    # Format the results into our GraphState structure
    retrieved_data = []
    for doc in docs:
        retrieved_data.append(
            RetrievedDocument(
                content=doc.page_content, 
                source_file=doc.metadata.get("source", "Unknown")
            )
        )
        
    # Update the shared state notebook
    return {"retrieved_docs": retrieved_data}